### ISSUE TITLE
Issues with genomic coordinates from Supplementary Table 1

### ISSUE THREAD

**Issue by zchiang** [CaiGroup/dna-seqfish-plus#1]
Hi,

I downloaded Supplementary Table 1 from Nature, which is described as "genomic coordinates of the 3,660 DNA loci used in DNA seqFISH+" and am running into an issue.

When I look at the table, I see 2 tabs labeled "1Mb_loci and "25kb_loci". However, the information on these tabs is identical - each has 1200 lines with names such as "chr1-HighRes-#1" - it seems like the "25kb_loci" information was mistakenly duplicated and the real "1Mb_loci" information is missing. Is there anywhere I can download the 1Mb genomic coordinates?

Thanks in advance for your assistance!

**Comment by zchiang** [comment]
Just in case it's helpful, I've attached the table downloaded from Nature here.
[41586_2020_3126_MOESM3_ESM.xlsx](https://github.com/CaiGroup/dna-seqfish-plus/files/10995827/41586_2020_3126_MOESM3_ESM.xlsx)

**Comment by y-takei** [comment]
Thank you very much for pointing out. Please find the corrected file below. 

[TableS1_target_loci.xlsx](https://github.com/CaiGroup/dna-seqfish-plus/files/10996748/TableS1_target_loci.xlsx)
